; Listing generated by Microsoft (R) Optimizing Compiler Version 19.26.28806.0 

	TITLE	D:\src\Github-Test\c\asm_demo\simple.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	_f1
PUBLIC	_f2
PUBLIC	_main
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
_DATA	SEGMENT
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
_DATA	ENDS
_DATA	SEGMENT
$SG9165	DB	'call f1(a,10) -> %d', 0aH, 00H
	ORG $+3
$SG9166	DB	'call f1(b,1000) --> %d', 0aH, 00H
_DATA	ENDS
; Function compile flags: /Odtp
; File D:\src\Github-Test\c\asm_demo\simple.c
_TEXT	SEGMENT
_main	PROC

; 25   : {

	push	ebp
	mov	ebp, esp

; 26   :     f2(123, 456);

	push	456					; 000001c8H
	push	123					; 0000007bH
	call	_f2
	add	esp, 8

; 27   :     return 0;

	xor	eax, eax

; 28   : }

	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File D:\src\Github-Test\c\asm_demo\simple.c
_TEXT	SEGMENT
_f2_y$ = -8						; size = 4
_f2_x$ = -4						; size = 4
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_f2	PROC

; 13   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8

; 14   :     int f2_x;
; 15   :     int f2_y;
; 16   : 
; 17   :     f2_x = f1(a, 10);

	push	10					; 0000000aH
	mov	eax, DWORD PTR _a$[ebp]
	push	eax
	call	_f1
	add	esp, 8
	mov	DWORD PTR _f2_x$[ebp], eax

; 18   :     printf("call f1(a,10) -> %d\n", f2_x);

	mov	ecx, DWORD PTR _f2_x$[ebp]
	push	ecx
	push	OFFSET $SG9165
	call	_printf
	add	esp, 8

; 19   : 
; 20   :     f2_y = f1(b, 1000);

	push	1000					; 000003e8H
	mov	edx, DWORD PTR _b$[ebp]
	push	edx
	call	_f1
	add	esp, 8
	mov	DWORD PTR _f2_y$[ebp], eax

; 21   :     printf("call f1(b,1000) --> %d\n", f2_y);

	mov	eax, DWORD PTR _f2_y$[ebp]
	push	eax
	push	OFFSET $SG9166
	call	_printf
	add	esp, 8

; 22   : }

	mov	esp, ebp
	pop	ebp
	ret	0
_f2	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File D:\src\Github-Test\c\asm_demo\simple.c
_TEXT	SEGMENT
_f1_x$ = -4						; size = 4
_a$ = 8							; size = 4
_n$ = 12						; size = 4
_f1	PROC

; 4    : {

	push	ebp
	mov	ebp, esp
	push	ecx

; 5    :     int f1_x = 1;

	mov	DWORD PTR _f1_x$[ebp], 1

; 6    :     if (a > 0)

	cmp	DWORD PTR _a$[ebp], 0
	jle	SHORT $LN2@f1

; 7    :         return f1_x + a + n;

	mov	eax, DWORD PTR _f1_x$[ebp]
	add	eax, DWORD PTR _a$[ebp]
	add	eax, DWORD PTR _n$[ebp]
	jmp	SHORT $LN1@f1
	jmp	SHORT $LN1@f1
$LN2@f1:

; 8    :     else
; 9    :         return f1_x - a - n;

	mov	eax, DWORD PTR _f1_x$[ebp]
	sub	eax, DWORD PTR _a$[ebp]
	sub	eax, DWORD PTR _n$[ebp]
$LN1@f1:

; 10   : }

	mov	esp, ebp
	pop	ebp
	ret	0
_f1	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT _printf
_TEXT	SEGMENT
__Result$ = -8						; size = 4
__ArgList$ = -4						; size = 4
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT

; 956  :     {

	push	ebp
	mov	ebp, esp
	sub	esp, 8

; 957  :         int _Result;
; 958  :         va_list _ArgList;
; 959  :         __crt_va_start(_ArgList, _Format);

	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax

; 960  :         _Result = _vfprintf_l(stdout, _Format, NULL, _ArgList);

	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	push	1
	call	___acrt_iob_func
	add	esp, 4
	push	eax
	call	__vfprintf_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax

; 961  :         __crt_va_end(_ArgList);

	mov	DWORD PTR __ArgList$[ebp], 0

; 962  :         return _Result;

	mov	eax, DWORD PTR __Result$[ebp]

; 963  :     }

	mov	esp, ebp
	pop	ebp
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT

; 644  :     {

	push	ebp
	mov	ebp, esp

; 645  :         return __stdio_common_vfprintf(_CRT_INTERNAL_LOCAL_PRINTF_OPTIONS, _Stream, _Format, _Locale, _ArgList);

	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR [eax]
	push	edx
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H

; 646  :     }

	pop	ebp
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT

; 90   :     {

	push	ebp
	mov	ebp, esp

; 91   :         static unsigned __int64 _OptionsStorage;
; 92   :         return &_OptionsStorage;

	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@9 ; `__local_stdio_printf_options'::`2'::_OptionsStorage

; 93   :     }

	pop	ebp
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
