"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
fibo_list = [1, 2]
even_list = []
"""whatever you put in the bracket adds as a single element of the list"""
while fibo_list[-1] + fibo_list[-2] < 4000000:
    fibo_list.append(fibo_list[-1]+fibo_list[-2])
for k in fibo_list:
    if k % 2 == 0:
        even_list.append(k)
"""print(fibo_list)"""
print(sum(even_list))

