"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
fibo_list = [1, 2]
"""whatever you put in the bracket adds as a single element of the list"""
while True:
    _next = fibo_list[-1] + fibo_list[-2]
    if _next < 4000000:
        fibo_list.append(_next)
    else:
        break

print(sum([x for x in fibo_list if x % 2 == 0]))
